# docker-compose.yml (Финальная версия для локальной разработки)

services:
  postgres:
    image: postgres:16-alpine
    container_name: social_pilot_postgres_local_dev
    env_file: ./.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: social_pilot_redis_local_dev
    ports:
      - "6379:6379"
    volumes:
      - redis_data_dev:/data
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Сервис для ARQ Worker, работающий с вашим локальным кодом
  worker:
    image: python:3.11-slim
    container_name: social_pilot_worker_local_dev
    command: >
      sh -c "pip install poetry && 
             poetry config virtualenvs.create false && 
             poetry install --no-root && 
             arq --watch . app.worker.WorkerSettings"
    volumes:
      - ./backend:/app/backend
    working_dir: /app/backend
    env_file:
      - ./.env
    restart: always
    depends_on:
      redis:
        condition: service_healthy

volumes:
  postgres_data_dev: {}
  redis_data_dev: {}
