services:
  postgres:
    image: postgres:16-alpine
    container_name: social_pilot_postgres_local_dev
    # --- ИСПРАВЛЕНИЕ ЗДЕСЬ: Указываем путь к .env в корне ---
    env_file: ./.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: social_pilot_redis_local_dev
    # Redis не использует переменные из .env, но для консистентности можно оставить
    ports:
      - "6379:6379"
    volumes:
      - redis_data_dev:/data
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data_dev: {}
  redis_data_dev: {}
