services:
  redis:
    image: redis:7-alpine
    container_name: social_pilot_redis_local_dev
    ports:
      - "6379:6379"
    volumes:
      - redis_data_dev:/data
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  worker:
    build:
      context: .
      dockerfile: worker.Dockerfile
    container_name: social_pilot_worker_local_dev
    volumes:
      - ./backend:/app
    env_file:
      - ./.env
    environment:
      - POSTGRES_SERVER=host.docker.internal
      - REDIS_HOST=redis
    restart: always
    depends_on:
      redis:
        condition: service_healthy

volumes:
  redis_data_dev: {}
