# --- Standard Group ---
- id: "like_feed"
  name: "Лайки в ленте новостей"
  description: "Анализирует вашу ленту новостей и проставляет лайки на посты, соответствующие фильтрам."
  has_filters: true
  has_count_slider: true
  modal_count_label: "Количество лайков"
  default_count: 50
  group: "standard"
- id: "add_recommended"
  name: "Добавление друзей"
  description: "Отправляет заявки в друзья пользователям из списка 'Возможные друзья', повышая охваты."
  has_filters: true
  has_count_slider: true
  modal_count_label: "Количество заявок"
  default_count: 20
  group: "standard"
- id: "accept_friends"
  name: "Прием заявок в друзья"
  description: "Автоматически принимает входящие заявки в друзья на основе заданных критериев."
  has_filters: true
  has_count_slider: false
  group: "standard"
- id: "remove_friends"
  name: "Очистка списка друзей"
  description: "Удаляет друзей по критериям: 'собачки', неактивность, пол. Поддерживает актуальность списка контактов."
  has_filters: true
  has_count_slider: true
  modal_count_label: "Максимум удалений"
  default_count: 100
  group: "standard"
- id: "view_stories"
  name: "Просмотр историй"
  description: "Автоматически просматривает все доступные истории, сигнализируя об активности вашего аккаунта."
  has_filters: false
  has_count_slider: false
  group: "standard"
- id: "birthday_congratulation"
  name: "Поздравления с Днем Рождения"
  description: "Автоматически отправляет персональные поздравления вашим друзьям в их день рождения."
  has_filters: false
  has_count_slider: false
  group: "standard"
- id: "mass_messaging"
  name: "Массовая рассылка"
  description: "Отправляет заданное сообщение вашим друзьям по гибким фильтрам. Идеально для информирования."
  has_filters: true
  has_count_slider: true
  modal_count_label: "Количество сообщений"
  default_count: 50
  group: "standard"
- id: "leave_groups"
  name: "Отписка от сообществ"
  description: "Автоматически покидает сообщества по заданным критериям (ключевые слова в названии)."
  has_filters: true
  has_count_slider: true
  modal_count_label: "Максимум отписок"
  default_count: 50
  group: "standard"
- id: "join_groups"
  name: "Вступление в группы"
  description: "Вступает в группы по ключевым словам для повышения информированности."
  has_filters: true
  has_count_slider: true
  modal_count_label: "Максимум вступлений"
  default_count: 20
  group: "standard"

# --- Online Group ---
- id: "eternal_online"
  name: "Статус 'Онлайн'"
  description: "Поддерживает статус 'онлайн' для вашего аккаунта по гибкому расписанию с имитацией человеческого поведения."
  has_filters: false
  has_count_slider: false
  group: "online"
  default_settings:
    mode: "schedule"
    humanize: true
    schedule_weekly:
      "1": { "is_active": true, "start_time": "09:00", "end_time": "23:00" }
      "2": { "is_active": true, "start_time": "09:00", "end_time": "23:00" }
      "3": { "is_active": true, "start_time": "09:00", "end_time": "23:00" }
      "4": { "is_active": true, "start_time": "09:00", "end_time": "23:00" }
      "5": { "is_active": true, "start_time": "09:00", "end_time": "22:00" }
      "6": { "is_active": false, "start_time": "11:00", "end_time": "20:00" }
      "7": { "is_active": false, "start_time": "11:00", "end_time": "20:00" }

# --- NEW: AI Group ---
- id: "ai_auto_responder"
  name: "ИИ-Автоответчик"
  description: "Автоматически отвечает на новые сообщения с помощью нейросети (Gemini/GPT), используя заданную личность."
  has_filters: true # Фильтры на диалоги (непрочитанные/новые)
  has_count_slider: true
  modal_count_label: "Максимум ответов за запуск"
  default_count: 10
  group: "ai"

# --- NEW: Parsing Group ---
- id: "parse_group_audience"
  name: "Парсер аудитории групп"
  description: "Собирает активную аудиторию (лайки, комментарии) из указанных сообществ конкурентов."
  has_filters: true
  has_count_slider: false
  group: "parsing"
- id: "export_conversation"
  name: "Экспорт диалогов"
  description: "Скачивает полную историю переписки с пользователем или из чата в формате JSON."
  has_filters: false
  has_count_slider: false
  group: "parsing"
