# backend/app/core/configs/automations.yml
# Этот файл определяет все возможные "действия", которые пользователь может
# ставить на автоматическое выполнение. Ручные действия определяются отдельно.

- id: "like_feed"
  name: "Авто-лайки в ленте"
  description: "Автоматически проставляет лайки на посты в вашей ленте новостей по расписанию."

- id: "add_recommended"
  name: "Авто-добавление друзей"
  description: "Отправляет заявки в друзья пользователям из списка рекомендованных по расписанию."

- id: "birthday_congratulation"
  name: "Авто-поздравления"
  description: "Автоматически поздравляет ваших друзей с днём рождения."

- id: "accept_friends"
  name: "Авто-прием заявок"
  description: "Автоматически принимает входящие заявки в друзья по заданным фильтрам."

- id: "remove_friends"
  name: "Авто-чистка друзей"
  description: "Удаляет друзей по заданным критериям (неактивность, пол и т.д.) по расписанию."

- id: "view_stories"
  name: "Авто-просмотр историй"
  description: "Автоматически просматривает истории ваших друзей и сообществ."

- id: "like_friends_feed"
  name: "Авто-лайки друзьям"
  description: "Проставляет лайки на последние посты на стенах ваших друзей по расписанию."