# backend/app/core/configs/automations.yml
# Единый источник правды обо всех возможных действиях в системе.
# Используется для автоматизаций, сценариев и ручного запуска.

- id: "like_feed"
  name: "Лайки в ленте"
  description: "Анализирует вашу ленту новостей и проставляет лайки на посты, соответствующие фильтрам."
  modal_count_label: "Количество лайков"
  has_filters: true

- id: "add_recommended"
  name: "Заявки в друзья"
  description: "Отправляет заявки в друзья пользователям из списка 'Возможные друзья', повышая охваты."
  modal_count_label: "Количество заявок"
  has_filters: true

- id: "accept_friends"
  name: "Прием заявок"
  description: "Автоматически принимает входящие заявки в друзья на основе заданных критериев (пол, возраст, онлайн и т.д.)."
  modal_count_label: null # Не имеет счетчика в модальном окне
  has_filters: true

- id: "remove_friends"
  name: "Чистка друзей"
  description: "Удаляет друзей по критериям: 'собачки', неактивность, пол. Поддерживает чистоту вашего списка контактов."
  modal_count_label: "Максимум удалений"
  has_filters: true

- id: "like_friends_feed"
  name: "Лайки друзьям"
  description: "Проявляет активность, проставляя лайки на последние посты на стенах ваших друзей."
  modal_count_label: "Количество лайков"
  has_filters: true

- id: "view_stories"
  name: "Просмотр историй"
  description: "Автоматически просматривает все доступные истории друзей и сообществ, сигнализируя об активности."
  modal_count_label: null
  has_filters: false

- id: "birthday_congratulation"
  name: "Поздравления с ДР"
  description: "Автоматически отправляет персональные поздравления вашим друзьям в их день рождения."
  modal_count_label: null
  has_filters: false

- id: "mass_messaging"
  name: "Массовая рассылка"
  description: "Отправляет заданное сообщение вашим друзьям по гибким фильтрам. Идеально для информирования."
  modal_count_label: "Максимум сообщений"
  has_filters: true

- id: "eternal_online"
  name: "Вечный онлайн"
  description: "Поддерживает статус 'онлайн' для вашего аккаунта 24/7, повышая видимость в поиске и списках друзей."
  modal_count_label: null
  has_filters: false