# backend/app/core/configs/plans.yml
# Единый источник правды о тарифных планах.
# Цены и скидки настраиваются здесь и автоматически применяются в API.

Expired:
  display_name: "Истёкший"
  description: "Срок действия вашего тарифа истек. Функционал ограничен."
  limits:
    daily_likes_limit: 0
    daily_add_friends_limit: 0
  available_features: []

Базовый:
  display_name: "Базовый (Пробный)"
  description: "Ознакомительный период на 14 дней для ручного запуска задач."
  features:
    - "Ручной запуск всех задач"
    - "Лимит 20 заявок в друзья / день"
    - "Лимит 400 лайков / день"
    - "Базовые фильтры аудитории"
    - "История последних 50 действий"
    - "Базовая аналитика аудитории"
  limits:
    daily_likes_limit: 400
    daily_add_friends_limit: 20
  available_features:
    - "like_feed"
    - "add_recommended"
    - "accept_friends"
    - "remove_friends"
    - "like_friends_feed"
    - "view_stories"

Plus:
  display_name: "Plus"
  base_price: 349.00 # Цена за 1 месяц
  currency: "RUB"
  description: "Для эффективного продвижения с помощью автоматизации ключевых действий."
  is_popular: true
  periods: # Гибкая настройка периодов и скидок
    - months: 3
      discount_percent: 10 # Скидка 10% за 3 месяца
    - months: 6
      discount_percent: 15
    - months: 12
      discount_percent: 25 # Самая выгодная скидка
  features:
    - "Все возможности Базового тарифа"
    - "Полный доступ к Центру Автоматизации"
    - "Вечный онлайн"
    - "Выбор скорости работы (Normal)"
    - "Лимит 60 заявок в друзья / день"
    - "Лимит 800 лайков / день"
    - "Полная история всех действий"
  limits:
    daily_likes_limit: 800
    daily_add_friends_limit: 60
  available_features:
    - "like_feed"
    - "add_recommended"
    - "accept_friends"
    - "remove_friends"
    - "like_friends_feed"
    - "view_stories"
    - "birthday_congratulation"
    - "eternal_online"

PRO:
  display_name: "PRO"
  base_price: 799.00
  currency: "RUB"
  description: "Максимум для SMM-специалистов и требовательных пользователей."
  is_popular: false
  periods:
    - months: 3
      discount_percent: 12
    - months: 6
      discount_percent: 20
    - months: 12
      discount_percent: 30
  features:
    - "Все возможности тарифа Plus"
    - "Конструктор сложных Сценариев"
    - "Массовая рассылка сообщений друзьям"
    - "Аналитика роста профиля (лайки)"
    - "Управление прокси-серверами"
    - "Выбор скорости работы (Fast/Slow)"
    - "Лимит 100 заявок в друзья / день"
    - "Лимит 1500 лайков / день"
  limits:
    daily_likes_limit: 1500
    daily_add_friends_limit: 100
  available_features: "*" # Все доступно