# --- backend/app/core/configs/plans.yml ---
Expired:
  display_name: Истекший
  description: "Срок действия вашего тарифа истек. Функциональность ограничена."
  features:
    - "Ограниченные дневные лимиты"
    - "История задач за 7 дней"
    - "Доступ к панели управления"
  limits:
    daily_likes_limit: 50
    daily_add_friends_limit: 5
    max_concurrent_tasks: 1
  available_features: []

Базовый:
  display_name: Базовый
  base_price: 0
  description: "Бесплатный 14-дневный доступ ко всем возможностям тарифа Plus."
  features:
    - "Все возможности тарифа Plus"
    - "Полный доступ на 14 дней"
    - "Поддержка по email"
  limits:
    daily_likes_limit: 1000
    daily_add_friends_limit: 40
    max_concurrent_tasks: 3
  available_features: "*" # Даем все на 14 дней

Plus:
  display_name: Plus
  base_price: 699
  is_popular: true
  description: "Идеальный старт для автоматизации рутинных задач и органического роста."
  periods:
    - months: 3
      discount_percent: 5
    - months: 6
      discount_percent: 15
    - months: 12
      discount_percent: 30
  features:
    - "1 аккаунт ВКонтакте"
    - "Все стандартные задачи"
    - "Базовая аналитика"
    - "Стандартные лимиты"
    - "Автоматизация по расписанию"
  limits:
    daily_likes_limit: 1000
    daily_add_friends_limit: 40
    max_concurrent_tasks: 3
  available_features:
    - 'like_feed'
    - 'add_recommended'
    - 'accept_friends'
    - 'remove_friends'
    - 'view_stories'
    - 'mass_messaging'
    - 'leave_groups'
    - 'join_groups'
    - 'birthday_congratulation'
    - 'eternal_online'
    - 'automations_center'
    - 'post_scheduler'

PRO:
  display_name: PRO
  base_price: 1499
  description: "Для продвинутых пользователей, которым нужны сценарии, прокси и глубокая аналитика."
  periods:
    - months: 3
      discount_percent: 5
    - months: 6
      discount_percent: 15
    - months: 12
      discount_percent: 30
  features:
    - "Все возможности Plus"
    - "Продвинутые сценарии"
    - "Управление прокси-серверами"
    - "Аналитика конверсии заявок"
    - "Тепловая карта активности"
    - "Гибкая настройка скорости"
    - "Повышенные лимиты"
  limits:
    daily_likes_limit: 2000
    daily_add_friends_limit: 60
    max_concurrent_tasks: 5
  available_features: "*"

Agency:
  display_name: Agency
  base_price: 2999
  description: "Для SMM-агентств и специалистов, ведущих несколько проектов одновременно."
  periods:
    - months: 3
      discount_percent: 5
    - months: 6
      discount_percent: 15
    - months: 12
      discount_percent: 30
  features:
    - "Все возможности PRO"
    - "До 5 аккаунтов ВКонтакте"
    - "(+499 ₽/мес. за доп. аккаунт)"
    - "Командный доступ"
    - "Максимальные лимиты"
    - "Приоритетная поддержка"
  limits:
    daily_likes_limit: 3000
    daily_add_friends_limit: 80
    max_concurrent_tasks: 10
    max_profiles: 5
    max_team_members: 5
  available_features: "*"