BASE:
  display_name: "Базовый"
  description: "Начальный тариф для ознакомления с базовыми возможностями."
  limits:
    daily_likes_limit: 50
    daily_add_friends_limit: 20
    daily_message_limit: 20
    daily_posts_limit: 5
    daily_join_groups_limit: 20
    daily_leave_groups_limit: 20
    max_concurrent_tasks: 1
  available_features:
    - "like_feed"
    - "add_recommended"
    - "accept_friends"
    - "view_stories"
    - "remove_friends"
    - "mass_messaging"
    - "leave_groups"
    - "join_groups"
PLUS:
  display_name: "Plus"
  description: "Расширенные возможности и увеличенные лимиты для активного продвижения."
  base_price: 399
  is_popular: true
  features:
    - "Все возможности Базового тарифа"
    - "Доступ к Центру автоматизаций"
    - "Планировщик постов"
    - "Аналитика роста профиля"
    - "Автопоздравления с ДР"
  periods:
    - months: 3
      discount_percent: 10
    - months: 6
      discount_percent: 15
    - months: 12
      discount_percent: 25
  limits:
    daily_likes_limit: 1000
    daily_add_friends_limit: 40
    daily_message_limit: 50
    daily_posts_limit: 20
    daily_join_groups_limit: 50
    daily_leave_groups_limit: 100
    max_concurrent_tasks: 2
  available_features:
    - "like_feed"
    - "add_recommended"
    - "accept_friends"
    - "view_stories"
    - "remove_friends"
    - "mass_messaging"
    - "leave_groups"
    - "join_groups"
    - "birthday_congratulation"
    - "eternal_online"
    - "automations_center"
    - "post_scheduler"
    - "profile_growth_analytics"
PRO:
  display_name: "PRO"
  description: "Максимальные лимиты и все функции для профессионалов и SMM-специалистов."
  base_price: 799
  features:
    - "Все возможности тарифа Plus"
    - "Продвинутые сценарии"
    - "Управление прокси"
    - "Быстрый/медленный режим работы"
  periods:
    - months: 3
      discount_percent: 10
    - months: 6
      discount_percent: 20
    - months: 12
      discount_percent: 30
  limits:
    daily_likes_limit: 5000
    daily_add_friends_limit: 80
    daily_message_limit: 100
    daily_posts_limit: 50
    daily_join_groups_limit: 100
    daily_leave_groups_limit: 200
    max_concurrent_tasks: 5
  available_features: "*"
AGENCY:
  display_name: "Agency"
  description: "Для агентств и команд. Управление несколькими аккаунтами."
  base_price: 1499
  features:
    - "Все возможности PRO-тарифа"
    - "Командный доступ"
    - "Управление до 5 профилей"
  periods:
    - months: 3
      discount_percent: 15
    - months: 6
      discount_percent: 25
    - months: 12
      discount_percent: 35
  limits:
    daily_likes_limit: 10000
    daily_add_friends_limit: 100
    daily_message_limit: 200
    daily_posts_limit: 100
    daily_join_groups_limit: 150
    daily_leave_groups_limit: 300
    max_concurrent_tasks: 10
    max_profiles: 5
    max_team_members: 5
  available_features: "*"
EXPIRED:
  display_name: "Expired"
  description: "Срок действия вашего тарифа истек."
  limits:
    daily_likes_limit: 0
    daily_add_friends_limit: 0
    daily_message_limit: 0
    daily_posts_limit: 0
    daily_join_groups_limit: 0
    daily_leave_groups_limit: 0
    max_concurrent_tasks: 1
  available_features: []
