"""Initial schema creation

Revision ID: 113e32753321
Revises: 36a5983f4aae
Create Date: 2025-09-20 01:06:44.052162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '113e32753321'
down_revision: Union[str, Sequence[str], None] = '36a5983f4aae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('ai_provider', sa.String(), nullable=True, comment="e.g., 'openai', 'google'"))
    op.add_column('users', sa.Column('encrypted_ai_api_key', sa.String(), nullable=True))
    op.add_column('users', sa.Column('ai_model_name', sa.String(), nullable=True, comment="e.g., 'gpt-4o', 'gemini-2.5-flash'"))
    op.add_column('users', sa.Column('ai_system_prompt', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'ai_system_prompt')
    op.drop_column('users', 'ai_model_name')
    op.drop_column('users', 'encrypted_ai_api_key')
    op.drop_column('users', 'ai_provider')
    # ### end Alembic commands ###
