"""add timezone

Revision ID: 4fd2c82de480
Revises: de786d187529
Create Date: 2025-09-17 22:23:16.523219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fd2c82de480'
down_revision: Union[str, Sequence[str], None] = 'de786d187529'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile_metrics', sa.Column('recent_likes_on_content', sa.Integer(), nullable=False))
    op.add_column('profile_metrics', sa.Column('total_content_likes', sa.Integer(), nullable=False))
    op.drop_column('profile_metrics', 'total_likes_on_content')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile_metrics', sa.Column('total_likes_on_content', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('profile_metrics', 'total_content_likes')
    op.drop_column('profile_metrics', 'recent_likes_on_content')
    # ### end Alembic commands ###
