"""add timezone

Revision ID: 52f4a3bbccab
Revises: 33410cd8ead9
Create Date: 2025-09-16 00:38:28.131485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52f4a3bbccab'
down_revision: Union[str, Sequence[str], None] = '33410cd8ead9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_stats', sa.Column('posts_created_count', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('users', sa.Column('daily_posts_limit', sa.Integer(), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'daily_posts_limit')
    op.drop_column('daily_stats', 'posts_created_count')
    # ### end Alembic commands ###
