"""add timezone

Revision ID: 628ec4205923
Revises: 1d6f17caaa7d
Create Date: 2025-09-19 21:18:23.914139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '628ec4205923'
down_revision: Union[str, Sequence[str], None] = '1d6f17caaa7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payments', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('fk_payments_user_id_users'), 'payments', type_='foreignkey')
    op.create_foreign_key(op.f('fk_payments_user_id_users'), 'payments', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_payments_user_id_users'), 'payments', type_='foreignkey')
    op.create_foreign_key(op.f('fk_payments_user_id_users'), 'payments', 'users', ['user_id'], ['id'])
    op.alter_column('payments', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
