"""Initial migration with all models

Revision ID: 63a1060f70c9
Revises: f7159ac9ff98
Create Date: 2025-09-11 21:37:25.903867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63a1060f70c9'
down_revision: Union[str, Sequence[str], None] = 'f7159ac9ff98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_stats', sa.Column('like_friends_feed_count', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('daily_stats', 'like_friends_feed_count')
    # ### end Alembic commands ###
