"""add timezone

Revision ID: 6722090930ea
Revises: 7b7f436974e7
Create Date: 2025-09-19 02:49:55.894037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6722090930ea'
down_revision: Union[str, Sequence[str], None] = '7b7f436974e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('global_settings',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_global_settings'))
    )
    op.create_index(op.f('ix_global_settings_key'), 'global_settings', ['key'], unique=False)
    op.create_table('banned_ips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('banned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], name=op.f('fk_banned_ips_admin_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_banned_ips'))
    )
    op.create_index(op.f('ix_banned_ips_ip_address'), 'banned_ips', ['ip_address'], unique=True)
    op.add_column('support_tickets', sa.Column('reopen_count', sa.Integer(), nullable=False))
    op.add_column('ticket_messages', sa.Column('attachment_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ticket_messages', 'attachment_url')
    op.drop_column('support_tickets', 'reopen_count')
    op.drop_index(op.f('ix_banned_ips_ip_address'), table_name='banned_ips')
    op.drop_table('banned_ips')
    op.drop_index(op.f('ix_global_settings_key'), table_name='global_settings')
    op.drop_table('global_settings')
    # ### end Alembic commands ###
