"""Add SentCongratulation model

Revision ID: a2b9746b0102
Revises: ea198fc5a733
Create Date: 2025-09-11 05:43:41.646739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2b9746b0102'
down_revision: Union[str, Sequence[str], None] = 'ea198fc5a733'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sent_congratulations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('friend_vk_id', sa.BigInteger(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'friend_vk_id', 'year', name='_user_friend_year_uc')
    )
    op.create_index(op.f('ix_sent_congratulations_friend_vk_id'), 'sent_congratulations', ['friend_vk_id'], unique=False)
    op.create_index(op.f('ix_sent_congratulations_user_id'), 'sent_congratulations', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sent_congratulations_user_id'), table_name='sent_congratulations')
    op.drop_index(op.f('ix_sent_congratulations_friend_vk_id'), table_name='sent_congratulations')
    op.drop_table('sent_congratulations')
    # ### end Alembic commands ###
