"""add timezone

Revision ID: c0a366ea130f
Revises: 34fa979080a2
Create Date: 2025-09-16 23:27:56.702204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0a366ea130f'
down_revision: Union[str, Sequence[str], None] = '34fa979080a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_stats', sa.Column('groups_joined_count', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('daily_stats', sa.Column('groups_left_count', sa.Integer(), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('daily_stats', 'groups_left_count')
    op.drop_column('daily_stats', 'groups_joined_count')
    # ### end Alembic commands ###
