"""add timezone

Revision ID: de786d187529
Revises: c0a366ea130f
Create Date: 2025-09-16 23:29:49.821842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de786d187529'
down_revision: Union[str, Sequence[str], None] = 'c0a366ea130f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('daily_join_groups_limit', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('users', sa.Column('daily_leave_groups_limit', sa.Integer(), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'daily_leave_groups_limit')
    op.drop_column('users', 'daily_join_groups_limit')
    # ### end Alembic commands ###
